### ISSUE TITLE
Set up reddit authentication

### ISSUE THREAD

**Issue by sanmadjack** [pcmasteratings/site#15]

**Comment by trevorstarick** [comment]
AFAIK Reddit doesn't have this at the time. https://www.reddit.com/r/redditdev/comments/2wkkg9/log_in_with_reddit_functionality/. A good idea/concept would be to link your reddit account with pcmr account.

**Comment by sanmadjack** [comment]
There is an imperfect mechanism for this, we've got an implementation going already.
