### ISSUE TITLE
Create database schema for storing game reviews

### ISSUE THREAD

**Issue by sanmadjack** [pcmasteratings/site#6]
https://docs.google.com/spreadsheets/d/1Tfz8KoQ-N6azvwT0FzudIjk6xC-3vM3AZehwzHFnHYo/edit#gid=0

**Comment by Naouak** [comment]
Shouldn't the scope of the website be defined fisrt ?
What do we want to stock ?

**Comment by Jenjen1324** [comment]
https://docs.google.com/spreadsheets/d/1Tfz8KoQ-N6azvwT0FzudIjk6xC-3vM3AZehwzHFnHYo/edit#gid=0

**Comment by ghost** [comment]
Since we have a pretty good schema setup right now, are we good to close this one?
